#define PRINTTOSTREAM(file, arg, ...) fprintf(file, arg "\n", __VA_ARGS__)
#define STDOUT(arg, ...) fprintf(stdout, "[%s] " arg "\n", __func__,__VA_ARGS__)
#define STDERR(arg, ...) fprintf(stderr, "[%s] " arg "\n", __func__,__VA_ARGS__)
#define WARNING(arg, ...)   fprintf(stderr, "[%s::WARNING]\033[1;33m " arg "\033[0m\n", __func__,__VA_ARGS__)
#define ERROR(arg, ...) fprintf(stderr, "[%s::ERROR]\033[1;31m " arg "\033[0m\n", __func__,__VA_ARGS__)
#define INFO(arg, ...)  fprintf(stderr, "[%s::INFO]\033[1;34m " arg "\033[0m\n", __func__,__VA_ARGS__)
#define SUCCESS(arg, ...)   fprintf(stderr, "[%s::SUCCESS]\033[1;32m " arg "\033[0m\n", __func__,__VA_ARGS__)
#define DEBUG(arg, ...) fprintf(stderr,"[%s::DEBUG]\033[1;35m Error occured at %s:%d. " arg "\033[0m\n",__func__, __FILE__, __LINE__ - 2, __VA_ARGS__)